version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/example"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
