apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: solr-ocrhighlighting
  description: An extension for Solr for indexing and highlighting OCR from common markup formats, with support for re-using existing external storage.
  annotations:
    github.com/project-slug: dbmdz/solr-ocrhighlighting
spec:
  type: library
  lifecycle: production
  owner: dbmdz
  system: solr
links:
  - url: https://dbmdz.github.io/solr-ocrhighlighting
    title: Public Documentation
    icon: docs
  - url: https://ocrhl.jbaiter.de/
    title: Demo
    icon: demo
