site_name: Solr OCR Highlighting Plugin
theme: readthedocs
nav:
    - Getting Started: getting_started.md
    - OCR Formats: formats.md
    - External Storage: external_storage.md
    - Example Setup: example.md
    - Query Parameters: queryparams.md
    - Frequently Asked Questions: faq.md
markdown_extensions:
    - attr_list
    - fenced_code
    - admonition
    - smarty
repo_url: https://github.com/dbmdz/solr-ocrhighlighting/